In [1]:
import gym
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Testing OpenAI Gym
Making an environment, running some episodes and steps to try out and learn the way to use OpenAI Gym.

In [2]:
env = gym.make('CartPole-v1')
cum_reward = 0

# Running for 20 episodes
for i_eps in range(20):
    observation = env.reset()
    last_reward = 0

    # For each episode run 100 timesteps
    for timesteps in range(100):
        env.render()

        # Random action done for each timesteps
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)

        print(observation, reward)
        cum_reward += reward
        if done:
            print(f'Episode finished after {timesteps} timesteps, got total reward of {cum_reward}')

            last_reward = cum_reward
            cum_reward = 0
            break

env.close()

84 -0.41174947] 1.0
[ 0.01991774  0.14553249  0.06548485 -0.0967663 ] 1.0
[ 0.02282839 -0.05046392  0.06354953  0.21583696] 1.0
[ 0.02181912  0.14369468  0.06786626 -0.05614206] 1.0
[ 0.02469301  0.33778122  0.06674342 -0.3266643 ] 1.0
[ 0.03144863  0.14177564  0.06021014 -0.01370256] 1.0
[ 0.03428415  0.33598473  0.05993609 -0.28679722] 1.0
[ 0.04100384  0.53020299  0.05420014 -0.55999083] 1.0
[ 0.0516079   0.724524    0.04300033 -0.83511727] 1.0
[ 0.06609838  0.52884183  0.02629798 -0.52922713] 1.0
[ 0.07667522  0.33335997  0.01571344 -0.22837503] 1.0
[ 0.08334242  0.52825389  0.01114594 -0.51606025] 1.0
[ 0.09390749  0.72321712  0.00082473 -0.8052101 ] 1.0
[ 0.10837184  0.91832776 -0.01527947 -1.09763348] 1.0
[ 0.12673839  1.11364751 -0.03723214 -1.3950709 ] 1.0
[ 0.14901134  0.91900809 -0.06513356 -1.11425782] 1.0
[ 0.1673915   1.11492194 -0.08741871 -1.42664119] 1.0
[ 0.18968994  0.92098213 -0.11595154 -1.16251072] 1.0
[ 0.20810958  0.72754514 -0.13920175 -0.908317  ] 1.0
[ 0.2226